API_HOST_URL: 'http://10.0.2.2:8000' # localhost is 10.0.2.2 in Android
ENVIRONMENT_DISPLAY_NAME: 'cungtienlen'
PLATFORM_NAME: 'CTL'
PLATFORM_DESTINATION_NAME: 'cungtienlen.com'
FEEDBACK_EMAIL_ADDRESS: 'support@cungtienlen.com'
